spring:
  config:
    import: file:env.properties

  datasource:
    url: jdbc:postgresql://localhost:5432/${DB_DATABASE}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

springdoc:
  api-docs:
    path: /api-docs
